package com.example.computingquiz;

public class QuestionsAndAnswers {

    // questions
    public static String questions[] = {
        "What does AI stand for?",
        "Which of the following is the branch of Artificial Intelligence?",
        "What is the function of an Artificial Intelligence “Agent”?",
        "Which of the following is not a type of Artificial Intelligence agent?",
        "Which of the following is not an application of artificial intelligence?",
        "Which of the following can improve the performance of an AI agent?",
        "Which of the following is an example of artificial intelligent agent/agents?",
        "What is the name of Artificial Intelligence which allows machines to handle vague information with a deftness that mimics human intuition?",
        "What does the Bayesian network provide?",
        "DARPA, the agency that has funded a great deal of American Artificial Intelligence research, is part of the Department of:",
        "What is Weak AI?",
        "If a robot can alter its own trajectory in response to external conditions, what it is considered to be?",
        "Where is one of the leading American robotics centers is the Robotics Institute located?",
        "What stage of the manufacturing process has been described as \"the mapping of function onto form\"?",
        "What was the first ai programming language called?",
        "What is an component of an Expert system?",
        "What kind of behavior does the stochastic environment posses?",
    };

    // options
    public static String options[][] = {
            {"Artificial Intelligence", "Advanced Intelligence", "Artificial Independence", "Advanced Independence"},
            {"Cyber forensics", "Network Design", "Machine Learning", "Full Stack Development"},
            {"Mapping of goal sequence to an action", "Work without the direct interference of the people", "Mapping of precept sequence to an action", "Mapping of environment sequence to an action"},
            {"Learning AI agent", "Goal-based AI agent", "Simple reflex AI agent", "Unity-based AI agent"},
            {"Face recognition system", "Chatbots", "LIDAR", "DBMS"},
            {"Perceiving", "Learning", "Observing", "All of the mentioned"},
            {"Autonomous Spacecraft", "Human", "Robot", "All of the mentioned"},
            {"Human intelligence", "Boolean logic", "Functional logic", "Functional logic"},
            {"Partial description of the domain", "Complete description of the problem", "Complete description of the domain", "None of the mentioned"},
            {"Education", "Defence", "Energy", "Justice"},
            {"A set of computer programs that produce output that would be considered to reflect intelligence if it were generated by humans.",
                    "The study of mental faculties through the use of mental models implemented on a computer",
                    "The embodiment of human intellectual capabilities within a computer",
                    "All of the above"},
            {"Mobile", "Open loop", "Intelligent", "Non servo"},
            {"RAND", "MIT", "CMU", "SRI"},
            {"Distribution", "Project Management", "Design", "Field Service"},
            {"Python", "IPL", "LISP", "Machine Language"},
            {"Inference Engine", "User Interface", "Knowledge Base", "All of the above"},
            {"Deterministic", "Local", "Primary", "Rational"},

    };

    // correct answers
    public static String answers[] = {
            "Artificial Intelligence",
            "Machine Learning",
            "Mapping of precept sequence to an action",
            "Unity-based AI agent",
            "DBMS",
            "Learning",
            "All of the mentioned",
            "Fuzzy Logic",
            "Complete description of the domain",
            "Defence",
            "The study of mental faculties through the use of mental models implemented on a computer.",
            "Intelligent",
            "CMU",
            "Design",
            "IPL",
            "All of the above",
            "Rational"

    };
}
